version: '2'
services:
  db:
    container_name: mysql01
    image: mysql:latest
    ports:
      - "3308:3306"
    env_file:
      - sec.env
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  sudoku:
    container_name: sudoku
    restart: always
    image: sudoku:0.0.1-SNAPSHOT
    env_file:
      - sec.env
    ports:
      - "8102:8102"
  sudoku-book:
    container_name: sudoku-book
    restart: always
    image: sudoku-book:0.0.1-SNAPSHOT
    env_file:
      - sec.env
    ports:
      - "8103:8103"
    depends_on:
      - db
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:3306

